version: '3.7'

services:
  lint:
    image: buildkite/plugin-linter:v2.1.0
    command: ['--id', 'elastic/oblt-google-secrets']
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - '.:/plugin:ro'
