agents:
  provider: gcp
  image: family/core-ubuntu-2204

steps:
  - label: ":test_tube: Unit Tests"
    command: make test

  - label: ":lint-roller: Plugin Lint"
    command: make plugin-lint

  - label: ":shell: ShellCheck"
    command: make shellcheck

  - label: ":google_cloud: E2E - Test Plugin Functionality"
    plugins:
      - elastic/oblt-google-secrets#${BUILDKITE_COMMIT}:
          secret: oblt-test-secret
          env-var: GOOGLE_SECRET_VALUE
    command: make e2e-test

notify:
  - slack: "#observablt-bots"
    if: build.branch == "main" && build.state == "failed"
